version: "3.9"

services:
  cheety-front:
    image: nginx:latest
    ports:
      - 3008:80
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    networks:
      - kn-net

networks:
  kn-net:
    driver: bridge